import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { RefreshCw, Sparkles, WandSparkles } from "lucide-react";
import { describeAiError, fetchCachedRukuSummary, getRukuSummary, isTauri } from "@/lib/ai";
import type { VerseWithWords } from "@/lib/types";
import { useContentLanguage } from "@/hooks/useProfile";
import { ayahRangeLabel, toParagraphs } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/feedback";
import { useToast } from "@/components/ui/toast";

/**
 * Summaries are shared across users, so this reads the cache first and only
 * asks the model when nothing is stored yet. Generation is user-initiated
 * rather than automatic, so opening a ruku is never gated on a network call.
 */
export function RukuSummaryCard({
  rukuNumber,
  surahName,
  verses,
}: {
  rukuNumber: number;
  surahName: string;
  verses: VerseWithWords[];
}) {
  const queryClient = useQueryClient();
  const toast = useToast();
  const language = useContentLanguage();

  const cached = useQuery({
    queryKey: ["ruku-summary", rukuNumber, language],
    staleTime: Infinity,
    queryFn: () => fetchCachedRukuSummary(rukuNumber, language),
  });

  const generate = useMutation({
    mutationFn: (force: boolean) =>
      getRukuSummary(
        {
          rukuNumber,
          surahName,
          verseRange: verses.length
            ? ayahRangeLabel(verses[0]!.ayah_number, verses[verses.length - 1]!.ayah_number)
            : "",
          verses: verses.map((v) => ({
            ayah_number: v.ayah_number,
            translation_en: v.translation_en,
            translation_ru: v.translation_ru,
          })),
        },
        language,
        { force },
      ),
    onSuccess: (data) => queryClient.setQueryData(["ruku-summary", rukuNumber, language], data),
    onError: (error) => toast(describeAiError(error), "error"),
  });

  const summary = cached.data;
  const busy = generate.isPending;

  return (
    <Card className="border-accent/25 bg-accent-soft/25 p-5">
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-center gap-2 text-[0.6875rem] font-medium uppercase tracking-wider text-accent-soft-fg">
          <Sparkles className="size-3.5" aria-hidden />
          What to take from this ruku
        </div>
        {summary && !busy ? (
          <button
            onClick={() => generate.mutate(true)}
            className="inline-flex items-center gap-1 text-[0.6875rem] text-fg-subtle transition-colors hover:text-fg"
            title="Regenerate this summary"
          >
            <RefreshCw className="size-3" aria-hidden />
            Regenerate
          </button>
        ) : null}
      </div>

      <div className="mt-3">
        {cached.isLoading || busy ? (
          <div className="space-y-2">
            <Skeleton className="h-3.5 w-full" />
            <Skeleton className="h-3.5 w-[95%]" />
            <Skeleton className="h-3.5 w-[88%]" />
            <Skeleton className="h-3.5 w-[60%]" />
          </div>
        ) : summary ? (
          <>
            <div className="prose-reading text-[0.9375rem] text-fg-muted" data-selectable>
              {toParagraphs(summary.summary).map((p, i) => (
                <p key={i}>{p}</p>
              ))}
            </div>
            {summary.model_used ? (
              <p className="mt-3 text-[0.6875rem] text-fg-subtle">
                Generated by {summary.model_used}
              </p>
            ) : null}
          </>
        ) : (
          <div className="flex flex-col items-start gap-3">
            <p className="text-[0.875rem] leading-relaxed text-fg-muted">
              {isTauri()
                ? "No summary yet for this ruku. Generate one and it will be saved for future readings."
                : "Summaries are generated by the desktop backend. Run the app with `pnpm app:dev` to enable them."}
            </p>
            {isTauri() ? (
              <Button size="sm" variant="primary" onClick={() => generate.mutate(false)}>
                <WandSparkles className="size-3.5" aria-hidden />
                Generate summary
              </Button>
            ) : null}
          </div>
        )}
      </div>
    </Card>
  );
}
